### ISSUE TITLE
Django 1.11 removes django.forms.widgets.CheckboxChoiceInput

### ISSUE THREAD

**Issue by markkuriekkinen** [apluslms/django-colortag#4]
This line https://github.com/Aalto-LeTech/django-colortag/blob/master/django_colortag/widgets.py#L34 uses `django.forms.widgets.CheckboxChoiceInput`, but Django 1.11 does not have that class (1.10 still does). There are other checkbox-related widgets in Django that still exist in new Django versions. Could they be used to replace the problematic line in django-colortag?

**Comment by raphendyr** [comment]
Easiest is to copy the classes from django 1.10 to colortag. A better solution would be portin colortag to django template based widgets.

**Comment by markkuriekkinen** [comment]
The widget `class ColortagSelectMultiple(widgets.CheckboxSelectMultiple)` is the only part in the public API affected by this issue, since `class CheckboxColortagInput(CheckboxChoiceInput)` and `class CheckboxColortagRenderer(widgets.CheckboxFieldRenderer)` should not be used anywhere outside the widgets.py. `ColortagSelectMultiple` could still inherit Django's `CheckboxSelectMultiple` widget, but instead of the old renderer class, it could use the new widget HTML templates (override the default template with a new one). 

However, I can not find any use-case for `ColortagSelectMultiple`. None of the projects I am aware of seem to make any use of this widget. Why does the widget `ColortagSelectMultiple` even exist?

**Comment by raphendyr** [comment]
> However, I can not find any use-case for ColortagSelectMultiple. None of the projects I am aware of seem to make any use of this widget. Why does the widget ColortagSelectMultiple even exist?

MOOC-Jutut`/feedback/filters.py` uses `ColortagChoiceFilter`, which uses `ColortagChoiceField`, which uses `ColortagSelectMultiple`.

With some effort, we can convert from widget classes to templates with their own names, as the template name is just a class variables. E.g.
```python
 class TextInput(Input):
    input_type = 'text'
    template_name = 'django/forms/widgets/text.html'
```
